# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb1b8481c87041c650a93b7de05b4b30c1ba1f896cf1b3321491216d391720d0fb1c99936a648a3b19407c895e2663f89f56d5e821e80a6832bc810b7a6b992

test:
  secret_key_base: d22e258743cfaff276cde964599632cde19ab92b7af8d1b70924e307bf87c0f095639fd6855a9b2f1581a11cecba205c43796a3a2ee9ff2147582822a21ffed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
